version: "3.7"

services:
  mc:
    image: itzg/minecraft-server:java8-multiarch
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 9225:9225
      - 25565:25565
      - 25575:25575
    environment:
      EULA: "TRUE"
      VERSION: "1.16.5"
      MEMORY: "2G"
      TYPE: "FORGE"
      FORGEVERSION: "36.2.22"
    volumes:
      - ./mc-data:/data
